<?php
require __DIR__.'/player-review.php';
require __DIR__.'/../includes/player-corrections.php';
use RadioRubben\Fotballrobot\PlayerCorrections as C;
use RadioRubben\Fotballrobot\PlayerReview as P;
use RadioRubben\Fotballrobot\PublicationGate as G;
$id=P::create('correction-test',$f,false,false);$s=P::state($id);P::decide($id,$s['version'],P::hash(get_post($id)),'approve','');
$original=get_post($id);$originalState=P::state($id);$originalQuality=get_post_meta($id,G::META,true);$mailBefore=count($mail);
$article=['title'=>'En tydeligere historie','lead'=>'Et kontrollert sammendrag.','paragraphs'=>['Registrerte opplysninger.'],'checks'=>[['claim'=>'Test','support'=>'facts']]];
$hash=P::hash($original);
$allowed=false;rejects(fn()=>C::prepare($id,$hash,$article),'Unauthorized correction rejected');$allowed=true;
rejects(fn()=>C::prepare($id,'stale',$article),'Stale published text rejected');
$correctionFail=true;rejects(fn()=>C::prepare($id,$hash,$article),'Failed facts cannot become correction');$correctionFail=false;
check(get_post($id)==$original&&P::state($id)===$originalState,'Preparation failures keep original text and approval');
$result=C::prepare($id,$hash,$article);$record=get_post_meta($id,C::META,true);
check($result['status']==='pending'&&get_post($id)==$original&&P::state($id)===$originalState,'Prepared correction does not modify public article');
check(get_post_meta($id,G::META,true)===$originalQuality&&count($mail)===$mailBefore,'Preparation preserves original quality and sends no mail');
rejects(fn()=>C::prepare($id,$hash,$article),'Pending revision cannot be overwritten');
$publish=false;rejects(fn()=>C::approve($id,$record['token']),'Publish capability required');$publish=true;
rejects(fn()=>C::approve($id,'stale'),'Exact proposal token required');
update_post_meta($id,'_thumbnail_id',999);rejects(fn()=>C::approve($id,$record['token']),'Concurrent image change invalidates approval');update_post_meta($id,'_thumbnail_id',813);
$bad=$record;$bad['post']['post_title']='Unreviewed';update_post_meta($id,C::META,$bad);rejects(fn()=>C::approve($id,$record['token']),'Changed proposal cannot reuse quality');update_post_meta($id,C::META,$record);
$options['rrfr_review_lock_'.$id]=time();rejects(fn()=>C::approve($id,$record['token']),'Approval shares normal per-story lock');unset($options['rrfr_review_lock_'.$id]);
$failNextUpdate=true;rejects(fn()=>C::approve($id,$record['token']),'Write failure reported');
check(get_post($id)==$original&&P::state($id)===$originalState&&get_post_meta($id,G::META,true)===$originalQuality,'Failed write restores original approval and public version');
C::approve($id,$record['token']);$updated=get_post($id);
check($updated->ID===$original->ID&&$updated->post_status==='publish'&&$updated->post_title===$article['title'],'Explicit approval updates same published post');
check(G::canPublish($id,$updated)&&P::state($id)['status']==='published','Normal gate validates the corrected version');
check(end(P::state($id)['history'])['action']==='correct'&&P::state($id)['version']===$originalState['version']+1,'Correction retains history and exact revision');
check(get_post_meta($id,'_thumbnail_id',true)===813&&count($mail)===$mailBefore,'Correction preserves image and sends no email');
rejects(fn()=>C::approve($id,$record['token']),'Correction approval cannot replay');
echo "Published correction checks passed\n";
