<?php
namespace RadioRubben\Fotballrobot;
self::allowed();$c=self::config();$notice=get_transient('rrfr_ms_notice_'.get_current_user_id());delete_transient('rrfr_ms_notice_'.get_current_user_id());
echo '<div class="wrap"><h1>Microsoft 365 e-post</h1>';
if($notice)echo '<div class="notice notice-info"><p>'.esc_html($notice).'</p></div>';
echo '<p>Sender spillerforslag fra <strong>'.esc_html(PlayerReview::FROM).'</strong> til <strong>'.esc_html(PlayerReview::TO).'</strong>.</p><p>Status: <strong>'.(!empty($c['tokens'])?'Tilkoblet – kontroller levering med test':'Ikke tilkoblet').'</strong></p><p>Denne tilkoblingen sender bare Fotballrobotens spillerforslag og testmeldinger. Andre WordPress-meldinger bruker eksisterende oppsett. Svar og kommentarer gis på godkjenningssiden.</p>';
echo '<h2>1. Registrer tilkoblingen hos Microsoft</h2><ol><li>Åpne <a href="https://entra.microsoft.com/" target="_blank" rel="noreferrer noopener">Microsoft Entra</a> → App registrations → New registration. Navn: Radio Rubben Fotballrobot. Velg bare kontoer i din organisasjon (single tenant).</li><li>Velg plattform <strong>Web</strong> og lim inn denne returadressen nøyaktig: <code>'.esc_html(self::callback()).'</code></li><li>Under API permissions: velg Microsoft Graph → Delegated permissions → <code>Mail.Send.Shared</code> og <code>offline_access</code>. Ingen lesetilgang til e-post trengs. Ikke velg Application permissions.</li><li>Under Certificates &amp; secrets: opprett en klienthemmelighet. Kopier verdien direkte til feltet nedenfor, ikke til chat. Noter utløpsdato for fornyelse.</li><li>Kopier Directory (tenant) ID og Application (client) ID fra Overview.</li></ol>';
echo '<h2>2. Lagre appopplysningene</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('rrfr_microsoft_mail');
echo '<input type="hidden" name="action" value="rrfr_microsoft_mail"><input type="hidden" name="operation" value="save">';
foreach(['tenant'=>'Directory (tenant) ID','client'=>'Application (client) ID'] as $key=>$label)echo '<p><label>'.esc_html($label).'<br><input class="regular-text" name="'.esc_attr($key).'" required value="'.esc_attr($c[$key]??'').'"></label></p>';
echo '<p><label>Client secret – Value<br><input class="regular-text" type="password" name="secret" autocomplete="new-password" value=""></label></p><p>'.(!empty($c['secret'])?'Hemmelighet er lagret. Tomt felt beholder den for samme app. ':'').'Hemmelighet og tilgangstokener lagres kryptert. Lagring kobler fra eksisterende forbindelse.</p><button class="button">Lagre oppsett</button></form>';
echo '<h2>3. Koble til og test</h2><p>Logg inn med Thomas-kontoen som har «Send som» for Fotballrobot-postkassen. Microsoft ber om samtykke til å sende e-post og fornye tilgangen. Tillatelsen begrenses av kontoens rettigheter; Fotballrobot-koden bruker bare avsenderen og mottakeren ovenfor.</p>';
foreach(['connect'=>'Koble til Microsoft 365','test'=>'Send test til Thomas','disconnect'=>'Koble fra'] as $op=>$label){echo '<form style="display:inline-block;margin-right:12px" method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('rrfr_microsoft_mail');echo '<input type="hidden" name="action" value="rrfr_microsoft_mail"><input type="hidden" name="operation" value="'.esc_attr($op).'"><button class="button">'.esc_html($label).'</button></form>';}
echo '<p>Akseptert av Microsoft betyr at sendingen er tatt imot, ikke at mottak er bekreftet. Ingen automatisk gjentakelse ved sendefeil. Ved uavklart sending: kontroller innboksen og Sendt før nytt forsøk.</p><p><a href="'.esc_url(PlayerReview::url()).'">Tilbake til artikkelforslag</a></p></div>';
