<?php
require __DIR__.'/bootstrap.php';
use RadioRubben\PlayerWidget\Live;
use RadioRubben\PlayerWidget\Service;
use RadioRubben\PlayerWidget\Sources;
$count=0;
function check($ok,$why){global $count;$count++;if(!$ok)throw new RuntimeException($why);}
$html=file_get_contents(__DIR__.'/fixtures/completed-match.html');
$m=['id'=>8989882,'kickoff'=>'2026-10-04T14:00:00+02:00','home'=>['id'=>209123,'name'=>'Sogndal Fotballklubb'],'away'=>['id'=>35897,'name'=>'Brann 2'],'venue'=>'Fosshaugane Campus','competition'=>'2. div kvinner avd. 1'];
$start=strtotime($m['kickoff']);$people=[3942773,3436482,3945433];
$r=Live::status($html,$m,$people,$start+6000);
check($r['phase']==='finished' && $r['roles'][3942773]===null,'Explicit final whistle removes live state');
$live=str_replace('Kampen er slutt','',$html);
$r=Live::status($live,$m,$people,$start+6000);
check($r['phase']==='live','Exact match events confirm live');
check($r['roles'][3942773]==='playing','Confirmed sub is playing');
check($r['roles'][3436482]==='off','Same substitution identifies outgoing player by ID');
check($r['roles'][3945433]==='bench','Unused substitute remains on bench');
check(Live::status($live,$m,[999],$start+6000)['roles'][999]===null,'Absent player never inferred');
check(Live::status($live,$m,$people,$start-60)['phase']==='scheduled','Clock before kickoff does not start game');
check(Live::status($live,$m,$people,$start+10801)['phase']==='unknown','Old incomplete event feed never stays live forever');
$red='<div class="timelineEventLine" id="999"><div class="timelineMinute">90</div><div class="timelineEventContent"><a href="/person/profil/?fiksId=3942773">Tiril</a><div>Utvisning</div></div></div>';
$redHtml=str_replace('</section>',$red.'</section>',$live);
check(Live::status($redHtml,$m,$people,$start+6000)['roles'][3942773]==='red','Dismissed player stops playing');
$plain=file_get_contents(__DIR__.'/fixtures/lineup.html');
check(Live::status($plain,$m,[3942773],$start+60)['roles'][3942773]==='starter','Kickoff alone cannot claim player is on field');
check(Live::interval($m,[],$start-4501)===21600,'Cheap background checks far from kickoff');
check(Live::interval($m,[],$start-4500)===60,'Squad window starts at 75 minutes');
check(Live::interval($m,[],$start+6000)===60,'Live minute polling');
check(Live::interval($m,['phase'=>'finished','finished_at'=>$start+6000],$start+6600)===300,'Five-minute final corrections');
check(Live::interval($m,['phase'=>'finished','finished_at'=>$start+6000],$start+9600)===3600,'Finished match backs off');
// Scheduler: two followed players share one NFF request; moving kickoff invalidates old roles.
$now=time();$future=gmdate(DATE_ATOM,$now+3600);$m['kickoff']=$future;
$today=wp_date('d.m.Y',$now+3600);$clock=wp_date('H:i',$now+3600);
$plain=str_replace(['04.10.2026','14:00'],[$today,$clock],$plain);
$m['kickoff']=(new DateTimeImmutable($future))->setTime((int)gmdate('H',$now+3600),(int)gmdate('i',$now+3600))->format(DATE_ATOM);
$posts=[1,2];foreach($posts as $id)$options['rrfr_player_'.$id]=['fiks_id'=>$id===1?3942773:111,'name'=>'Player '.$id,'enabled'=>true,'group'=>'bomlo-away','snapshot'=>['clubs'=>[781=>['name'=>'Brann']],'stats'=>[['year'=>(int)wp_date('Y'),'team_id'=>35897,'team'=>'Brann 2']]]];
$options[Service::SETTINGS]=['revision'=>1,'enabled'=>true,'players'=>[]];
$options[Service::CACHE]=['teams'=>[35897=>['club_id'=>781,'name'=>'Brann 2','checked_at'=>$now,'attempted_at'=>$now,'matches'=>[8989882=>$m]]],'matches'=>[]];
$remote[Sources::url('match',8989882)]=['status'=>200,'body'=>$plain];
Live::tick();
check(count(array_filter($calls,fn($r)=>$r['url']===Sources::url('match',8989882)))===1,'One request per match regardless of player count');
$cache=Service::cache();check($cache['matches'][8989882]['roles']===[3942773=>'starter',111=>'bench'],'Shared response mapped to both exact player IDs');
$n=count($calls);Live::tick();check(count($calls)===$n,'Repeated job inside interval makes no request');
$cache['matches'][8989882]['attempted_at']=$now-61;$options[Service::CACHE]=$cache;Live::tick();
check(count($calls)===$n+1,'One new match request at next minute without MyGame request');
$cache=Service::cache();$cache['matches'][8989882]['lineup_checked_at']=$now-151;$options[Service::CACHE]=$cache;
check(Service::cards()[0]['players'][3942773]['role']===null,'Stale live lineup expires independently');
echo "$count live checks passed\n";
